# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d394b9d33499dcc63503a5c8435cb03273aa2a73de8ed8685512b3448e9ad0810b913af2d6fe290cf57ecbf0cd956fe9f054f7dabaa592cce5b52f259424fdb9

test:
  secret_key_base: 5f4a62acf181c11c479320343093d6e72ebb2a339aee4c95a91e1a101f8f35d2a4fbd3d5d06ffaf71ff45e012544682b4ab38af57a08936c649b70da3cd2c90d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
